### ISSUE TITLE
Syncing issues 

### ISSUE THREAD

**Issue by taofineberg** [TheNetworkGuy/netbox-zabbix-sync#15]
Zabbix v6.2
Netbox v3.2.5

I am having a problem syncing. 
This was the first error I got after running 

netbox_zabbix_sync.py -c -H -t -v

`Traceback (most recent call last):
  File "netbox_zabbix_sync.py", line 716, in <module>
    main(args)
  File "netbox_zabbix_sync.py", line 79, in main
    if(device.promoteMasterDevice()):
  File "netbox_zabbix_sync.py", line 254, in promoteMasterDevice
    masterid = self.getClusterMaster()
  File "netbox_zabbix_sync.py", line 246, in getClusterMaster
    return self.nb.virtual_chassis.master.id
AttributeError: 'NoneType' object has no attribute 'id'
`

now running this I get error:
python3   netbox_zabbix_sync.py -c  -t -v
`Traceback (most recent call last):
  File "netbox_zabbix_sync.py", line 716, in <module>
    main(args)
  File "netbox_zabbix_sync.py", line 133, in main
    device.createInZabbix(zabbix_groups, zabbix_templates,
  File "netbox_zabbix_sync.py", line 384, in createInZabbix
    if(not self.getZabbixGroup(groups)):
  File "netbox_zabbix_sync.py", line 299, in getZabbixGroup
    self.group_id = group['groupid']
KeyError: 'groupid'
`

only the Host groups are been added to Zabbix no hosts 

Any assisantnce would be very helfpfull 

Tao

**Comment by TheNetworkGuy** [comment]
Thanks for reporting! :)

It looks like the ID field in Netbox is not returned via the API. I'll check the release notes for version 3.2. Coming back to this issue later today.

**Comment by taofineberg** [comment]
ZBX v6.2.2
Netbox v3.3.2

Thank you for your swift response. I have setup a LAB environment to test so clean database for both ZBX and Netbox. 

1) create a single device with all relevant info - Sync worked but with error
`
2022-09-06 11:00:14,940 - Netbox-Zabbix-sync - DEBUG - Added Tenant FineNet to hostgroup format of RackSwitch1.
2022-09-06 11:00:14,975 - Netbox-Zabbix-sync - INFO - Added hostgroup 'Geneva/FineNet/Mikrotik/Router'.
2022-09-06 11:00:15,002 - Netbox-Zabbix-sync - DEBUG - Found group Geneva/FineNet/Mikrotik/Router for host RackSwitch1.
2022-09-06 11:00:15,002 - Netbox-Zabbix-sync - DEBUG - Found template ID 10449 for host RackSwitch1.
Traceback (most recent call last):
  File "netbox_zabbix_sync.py", line 716, in <module>
    main(args)
  File "netbox_zabbix_sync.py", line 133, in main
    device.createInZabbix(zabbix_groups, zabbix_templates,
  File "netbox_zabbix_sync.py", line 409, in createInZabbix
    self.nb.save()
  File "/usr/local/lib/python3.8/dist-packages/pynetbox/core/response.py", line 538, in save
    if req.patch(updates):
  File "/usr/local/lib/python3.8/dist-packages/pynetbox/core/query.py", line 427, in patch
    return self._make_call(verb="patch", data=data)
  File "/usr/local/lib/python3.8/dist-packages/pynetbox/core/query.py", line 287, in _make_call
    raise RequestError(req)
pynetbox.core.query.RequestError: The request failed with code 400 Bad Request: {'__all__': ["Invalid value for custom field 'zabbix_hostid': Value must be a string."]}
`
2) update  from planned to active to see if it updates in zabbix - does not make any changes in Zabbix
   Output: 
 ` 
2022-09-06 11:26:08,799 - Netbox-Zabbix-sync - DEBUG - Added Tenant FineNet to hostgroup format of RackSwitch1.
2022-09-06 11:26:08,826 - Netbox-Zabbix-sync - WARNING - Unable to add RackSwitch1 to Zabbix: host already present.
`

3) create a 2nd  device in same site with all relevant info and set to active  - Get error 
  Output:
`
2022-09-06 12:18:30,831 - Netbox-Zabbix-sync - DEBUG - Added Tenant FineNet to hostgroup format of RackSwitch1.
2022-09-06 12:18:30,865 - Netbox-Zabbix-sync - WARNING - Unable to add RackSwitch1 to Zabbix: host already present.
2022-09-06 12:18:30,899 - Netbox-Zabbix-sync - DEBUG - Added Tenant FineNet to hostgroup format of Router2.
Traceback (most recent call last):
  File "netbox_zabbix_sync.py", line 716, in <module>
    main(args)
  File "netbox_zabbix_sync.py", line 133, in main
    device.createInZabbix(zabbix_groups, zabbix_templates,
  File "netbox_zabbix_sync.py", line 384, in createInZabbix
    if(not self.getZabbixGroup(groups)):
  File "netbox_zabbix_sync.py", line 299, in getZabbixGroup
    self.group_id = group['groupid']
KeyError: 'groupid'

`

4) remove the host group and device from Zabbix and run the script again. -  host group and 1st device gets added only 
Output:
`
2022-09-06 12:22:29,850 - Netbox-Zabbix-sync - DEBUG - Added Tenant FineNet to hostgroup format of RackSwitch1.
2022-09-06 12:22:29,906 - Netbox-Zabbix-sync - INFO - Added hostgroup 'Geneva/FineNet/Mikrotik/Router'.
2022-09-06 12:22:29,938 - Netbox-Zabbix-sync - DEBUG - Found group Geneva/FineNet/Mikrotik/Router for host RackSwitch1.
2022-09-06 12:22:29,939 - Netbox-Zabbix-sync - DEBUG - Found template ID 10449 for host RackSwitch1.
Traceback (most recent call last):
  File "netbox_zabbix_sync.py", line 716, in <module>
    main(args)
  File "netbox_zabbix_sync.py", line 133, in main
    device.createInZabbix(zabbix_groups, zabbix_templates,
  File "netbox_zabbix_sync.py", line 409, in createInZabbix
    self.nb.save()
  File "/usr/local/lib/python3.8/dist-packages/pynetbox/core/response.py", line 538, in save
    if req.patch(updates):
  File "/usr/local/lib/python3.8/dist-packages/pynetbox/core/query.py", line 427, in patch
    return self._make_call(verb="patch", data=data)
  File "/usr/local/lib/python3.8/dist-packages/pynetbox/core/query.py", line 287, in _make_call
    raise RequestError(req)
pynetbox.core.query.RequestError: The request failed with code 400 Bad Request: {'__all__': ["Invalid value for custom field 'zabbix_hostid': Value must be a string."]}
'
5)  run the script again 
Output: 
`
2022-09-06 12:28:23,189 - Netbox-Zabbix-sync - DEBUG - Added Tenant FineNet to hostgroup format of RackSwitch1.
2022-09-06 12:28:23,219 - Netbox-Zabbix-sync - WARNING - Unable to add RackSwitch1 to Zabbix: host already present.
2022-09-06 12:28:23,245 - Netbox-Zabbix-sync - DEBUG - Added Tenant FineNet to hostgroup format of Router2.
Traceback (most recent call last):
  File "netbox_zabbix_sync.py", line 716, in <module>
    main(args)
  File "netbox_zabbix_sync.py", line 133, in main
    device.createInZabbix(zabbix_groups, zabbix_templates,
  File "netbox_zabbix_sync.py", line 384, in createInZabbix
    if(not self.getZabbixGroup(groups)):
  File "netbox_zabbix_sync.py", line 299, in getZabbixGroup
    self.group_id = group['groupid']
KeyError: 'groupid'
`


Let me know if you would like me to test anything else
Thank you so much for looking into this 

Kind Regards 

Tao

**Comment by TheNetworkGuy** [comment]
Okay so for your first reply, i managed to run the script using NB 3.3.2 and Zabbix 6.2.2 without any issues first try. So what i would assume is that you actually didn't define the master under the Virtual Chassis configuration, which is why Netbox doesn't return an ID.

I'll fix the script so that this error is properly handled instead of this ugly business. As for your second message haven't taken a look at it yet but will do once i fix (or properly escape) your initial problem.

**Comment by TheNetworkGuy** [comment]
So it turns out that the rest of the problems we're all connected to the Zabbix API. For some reason the output worked fine up until 5.0. I've modified the Zabbix config (especially parts of the consistency check, which is why you didn't have any problems on the first run) to work with 6.0 and 6.2. The config still works for Zabbix 4.0 and 5.0 so all of the currently supported Zabbix versions are working which is good enough for me.

If you have any other problems feel free to post them in a new bug report. Thanks for bringing my attention to this!

**Comment by TheNetworkGuy** [comment]
Just to reopen this, can you confirm that your issues have been resolved?

**Comment by taofineberg** [comment]
Thank you, 
I have tested and it is working now. 
Appreciate your commitment to keeping this update
